id: P0881EB8A
initial_creation_type: input
source_metadata:
  title: Lelung Shepé Dorje Series
  language: bo
  description: 'Texts by and about the Geluk master Lelung Shepé Dorje (sle lung bzhad
    pa''i rdo rje, 1697–1740), a prolific author famed for his writings on the dharmapālas:'
  volume:
    86a0fb689c3a44df837c390a5b6497db:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: Aspiration Prayers
    9d852e7b4cf34698ac54587267777f15:
      title: 'The Magical Lasso: A Prayer of Aspiration to Accomplish Khecara'
      parent: Aspiration Prayers
created_at: '2022-03-01T00:34:32.746913'
last_modified_at: '2022-03-01T00:34:32.746916'
statistics:
  total_words: 2078
  total_non_words: 126
quality:
  non_words_ratio: 0.06
